### ISSUE TITLE
Could I use this in Windows?

### ISSUE THREAD

**Issue by ZhengdiYu** [Oldpan/Pytorch-Memory-Utils#13]
When I was using it, it says:

```
Traceback (most recent call last):
  File "F:xxx/CDF/test.py", line 63, in <module>
    gpu_tracker.track()
  File "F:\xxx\CDF\utils\Memory\gpu_mem_track.py", line 53, in track
    pynvml.nvmlInit()
  File "F:\Anaconda\envs\x\lib\site-packages\pynvml\nvml.py", line 749, in nvmlInit
    check_return(ret)
  File "F:\Anaconda\envs\x\lib\site-packages\pynvml\nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_Unknow
```n: Unknown Error

**Comment by Hezhexi2002** [comment]
It works?
